/* HOME PAGE */
export const GET_HOMEPAGE_DATA = 'GET_HOMEPAGE_DATA';
export const HOMEPAGE_DATA = 'HOMEPAGE_DATA';
export const HOMEPAGE_ERROR = 'HOMEPAGE_ERROR';
// export const SET_CATEGORIES = 'SET_CATEGORIES'
// export const SET_STAT = 'SET_STAT'

/* Dashboard Page */
export const ACTIVE_PART = 'ACTIVE_PART';
export const SET_POPUP = 'SET_POPUP';
export const CLEAR_POPUP = 'CLEAR_POPUP';

/* Courses List Page */
export const GET_COURSES_DATA = 'GET_COURSES_DATA';
export const GET_COURSES_SEARCH_DATA = 'GET_COURSES_SEARCH_DATA';
export const DISPLAY_MOBILE_FILTER_MENU = 'DISPLAY_MOBILE_FILTER_MENU';
export const SET_COURSES_IS_FREE = 'SET_COURSES_IS_FREE';
export const SET_COURSES_SORT = 'SET_COURSES_SORT';
export const ADD_COURSES_ACADEMY_FILTER = 'ADD_COURSES_ACADEMY_FILTER';
export const ADD_COURSES_TYPE_FILTER = 'ADD_COURSES_TYPE_FILTER';
export const REMOVE_COURSES_ACADEMY_FILTER = 'REMOVE_COURSES_ACADEMY_FILTER';
export const REMOVE_COURSES_TYPE_FILTER = 'REMOVE_COURSES_TYPE_FILTER';
export const CLEAR_COURSES_FILTERS = 'CLEAR_COURSES_FILTERS';
export const SET_PAGE = 'SET_PAGE';

/* Header Content */
export const SET_USER_CHECK = 'SET_USER_CHECK';
export const SHOW_USER_MENU = 'SHOW_USER_MENU';
export const SHOW_CATEGORY_DESKTOP_MENU = 'SHOW_CATEGORY_DESKTOP_MENU';
export const SHOW_CATEGORY_MOBILE_MENU = 'SHOW_CATEGORY_MOBILE_MENU';
export const GET_MENU_CATEGORIES = 'GET_MENU_CATEGORIES';

/* Footer Content */
export const GET_TOP_CATEGORIES = 'GET_TOP_CATEGORIES';
export const SHOW_USER_HEADER_DATA = 'SHOW_USER_HEADER_DATA';

/* Search Functionality */
export const SET_KEYWORDS = 'SET_KEYWORDS';
export const SEARCH_COURSES = 'SEARCH_COURSES';
export const AUTO_SUGGEST = 'AUTO_SUGGEST';
export const HIDE_SUGGEST = 'HIDE_SUGGEST';
export const SEARCH_CATEGORY_COURSES = 'SEARCH_CATEGORY_COURSES';

/* Course Page */
export const GET_COURSE_COMMENTS = 'GET_COURSE_COMMENTS';
